{% set version = "3.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tergm
  version: {{ version|replace("-", "_") }}

source:
  fn: tergm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tergm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tergm/tergm_{{ version }}.tar.gz
  sha256: 65b4f80799342a596ea5b14371f3982f1b611faa02ecabbfd5c79a9b4a66f85c

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]

  host:
    - r-base
    - r-mass
    - r-coda
    - r-ergm >=3.8
    - r-network >=1.13
    - r-networkdynamic >=0.8.1
    - r-nlme
    - r-robustbase >=0.9_10
    - r-statnet.common >=4.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-coda
    - r-ergm >=3.8
    - r-network >=1.13
    - r-networkdynamic >=0.8.1
    - r-nlme
    - r-robustbase >=0.9_10
    - r-statnet.common >=4.0

test:
  commands:
    - $R -e "library('tergm')"           # [not win]
    - "\"%R%\" -e \"library('tergm')\""  # [win]

about:
  home: http://www.statnet.org
  license: GPL-3
  summary: An integrated set of extensions to the 'ergm' package to analyze and simulate network
    evolution based on exponential-family random graph models (ERGM). 'tergm' is a part
    of the 'statnet' suite of packages for network analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - stevierene82
