{% set version = '3.5.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tergm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tergm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tergm/tergm_{{ version }}.tar.gz
  sha256: 65b4f80799342a596ea5b14371f3982f1b611faa02ecabbfd5c79a9b4a66f85c

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-coda
    - r-ergm >=3.9
    - r-network >=1.13
    - r-networkdynamic >=0.8.1
    - r-nlme
    - r-robustbase >=0.9_10
    - r-statnet.common >=4.1.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-coda
    - r-ergm >=3.9
    - r-network >=1.13
    - r-networkdynamic >=0.8.1
    - r-nlme
    - r-robustbase >=0.9_10
    - r-statnet.common >=4.1.0

test:
  commands:
    - $R -e "library('tergm')"           # [not win]
    - "\"%R%\" -e \"library('tergm')\""  # [win]

about:
  home: http://www.statnet.org
  license: GPL-3
  summary: An integrated set of extensions to the 'ergm' package to analyze and simulate network
    evolution based on exponential-family random graph models (ERGM). 'tergm' is a part
    of the 'statnet' suite of packages for network analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: tergm
# Version: 3.5.2
# Date: 2018-08-18
# Title: Fit, Simulate and Diagnose Models for Network Evolution Based on Exponential-Family Random Graph Models
# Authors@R: c( person("Pavel N.", "Krivitsky", role=c("aut","cre"), email="pavel@uow.edu.au", comment=c(ORCID="0000-0002-9101-3362")), person("Mark S.", "Handcock", role=c("aut","ths"), email="handcock@stat.ucla.edu"), person("David R.", "Hunter", role=c("ctb"), email="dhunter@stat.psu.edu"), person("Steven M.", "Goodreau", role=c("ctb","ths"), email="goodreau@u.washington.edu"), person("Martina", "Morris", role=c("ctb","ths"), email="morrism@u.washington.edu"), person("Nicole Bohme", "Carnegie", role=c("ctb"), email="nicole.carnegie@nyu.edu"), person("Carter T.", "Butts", role=c("ctb"), email="buttsc@uci.edu"), person("Ayn", "Leslie-Cook", role=c("ctb"), email="aynlc3@uw.edu"), person("Skye", "Bender-deMoll", role=c("ctb"), email="skyebend@skyeome.net"), person("Li","Wang",role=c("ctb"),email="lxwang@gmail.com"), person("Kirk","Li",role=c("ctb"),email="kirkli@uw.edu"))
# LinkingTo: ergm
# Depends: ergm (>= 3.9), network (>= 1.13), networkDynamic (>= 0.8.1)
# Imports: robustbase (>= 0.9-10), coda, nlme, MASS, statnet.common (>= 4.1.0)
# Suggests: lattice, parallel, rmarkdown, knitr
# BugReports: https://github.com/statnet/tergm/issues
# Description: An integrated set of extensions to the 'ergm' package to analyze and simulate network evolution based on exponential-family random graph models (ERGM). 'tergm' is a part of the 'statnet' suite of packages for network analysis.
# License: GPL-3 + file LICENSE
# URL: http://www.statnet.org
# VignetteBuilder: rmarkdown, knitr
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# Collate: 'InitConstraint.R' 'InitErgmTerm.duration.R' 'InitMHP.DynMLE.R' 'InitMHP.DynMLE.blockdiag.R' 'InitMHP.DynMoME.R' 'coef.stergm.R' 'combine.networks.R' 'control.logLik.stergm.R' 'control.simulate.stergm.R' 'control.stergm.R' 'ergm.godfather.R' 'gof.stergm.R' 'impute.network.list.R' 'is.lasttoggle.R' 'logLik.stergm.R' 'mcmc.diagnostics.stergm.R' 'print.stergm.R' 'simulate.stergm.R' 'stergm.CMLE.R' 'stergm.EGMME.GD.R' 'stergm.EGMME.R' 'stergm.EGMME.SA.R' 'stergm.EGMME.initialfit.R' 'stergm.R' 'tergm-deprecated.R' 'stergm.getMCMCsample.R' 'stergm.utils.R' 'summary.statistics.networkDynamic.R' 'summary.stergm.R' 'zzz.R'
# NeedsCompilation: yes
# Packaged: 2018-08-18 10:41:08 UTC; pavel
# Author: Pavel N. Krivitsky [aut, cre] (<https://orcid.org/0000-0002-9101-3362>), Mark S. Handcock [aut, ths], David R. Hunter [ctb], Steven M. Goodreau [ctb, ths], Martina Morris [ctb, ths], Nicole Bohme Carnegie [ctb], Carter T. Butts [ctb], Ayn Leslie-Cook [ctb], Skye Bender-deMoll [ctb], Li Wang [ctb], Kirk Li [ctb]
# Maintainer: Pavel N. Krivitsky <pavel@uow.edu.au>
# Repository: CRAN
# Date/Publication: 2018-08-18 15:40:03 UTC
