{% set version = "4.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tergm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tergm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tergm/tergm_{{ version }}.tar.gz
  sha256: dcf5a26cc2c4d165766706af08f8ea4f36e328158f5b682490c2a351f7fbda69

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-coda >=0.19.2
    - r-ergm >=4.5.0
    - r-ergm.multi >=0.2.0
    - r-mass >=7.3.51.4
    - r-network >=1.18.0
    - r-networkdynamic >=0.11.3
    - r-nlme >=3.1.139
    - r-purrr
    - r-robustbase >=0.93.5
    - r-statnet.common >=4.9.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-coda >=0.19.2
    - r-ergm >=4.5.0
    - r-ergm.multi >=0.2.0
    - r-mass >=7.3.51.4
    - r-network >=1.18.0
    - r-networkdynamic >=0.11.3
    - r-nlme >=3.1.139
    - r-purrr
    - r-robustbase >=0.93.5
    - r-statnet.common >=4.9.0

test:
  commands:
    - $R -e "library('tergm')"           # [not win]
    - "\"%R%\" -e \"library('tergm')\""  # [win]

about:
  home: http://www.statnet.org
  dev_url: https://github.com/statnet/tergm
  license: GPL-3.0-only
  summary: An integrated set of extensions to the 'ergm' package to analyze and simulate network evolution based on exponential-family random graph models (ERGM). 'tergm' is a part of the 'statnet' suite of packages for network analysis.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82
