appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PFBZ4N68TqE5ngxEx1ShxjHxo32IQGjuUq9ynA3Et9hIvU09FSQ+nvYVn5XMrgJG1KIl9OHHkxVJUK8puv+YQGAsb2ICQ1rDQa4OqjzayEXLpOxxLQP3VPg21dCtairOm7+dkEMQz9yEo6FRMmDYwFst7e4S6bx5Wv4yFfRP2PXxv4x0t1vQXVVy5o9gFxnpS/nrXweAbIkfqpuHPef0U94TshlPHBd3qPUVvGVLMI71QLmYbHEXEVbGn0GqX0QDs4hn6vIBuDvk2k2wSvTToHiJQGxR9fdTNtwVdZ0W2kdjFU99r7nd5BCBuZeG3OOraShaimlr6YfujwmaMYimzB4IUNQzNrHwbFYY03JLw6ShY10uBiIbjTy/riEtNm6CFpDgNncnc1BmY+U4AXeVqSj5WzT0s8siIG/aX9YKLIpFuxSD1IQVm8V7xZBlcsjLjYPErxprKarUnzfnOt2meM319YNMITrrL6x5nnJ3ys44L8ZftppFPfgTZyi+Fvi8tkEBD2rL7Ullp29/mYFF66bCPanYPpmxNODmfEud3we3B/OXXAVs/VeyXIJnRe6RkyzOVzlnSRCJLLMjMyxZoeFPY3qUevTfp1t6ZSxjTtwWUOM4xSlWn2PS2GILGQ8bMuOWZObeoKosk1wOI46nDacRbKnwUQurWSgAmuO99xg=
conda_forge_output_validation: true
